product_1=input("what will product_1 :")
price_1=input("price of the product_1 :")
quantity_1=input("quantity of the product_1 :")
product_2=input("what will product_2 :")
price_2=input("price of the product_2 :")
quantity_2=input("quantity of the product_2 :")
product_3=input("what will product_3 :")
price_3=input("price of the product_3 :")
quantity_3=input("quantity of the product_3 :")

result_1=float(price_1)*float(quantity_1)
result_2=float(price_2)*float(quantity_2)
result_3=float(price_3)*float(quantity_3)
print()
print("the total price of product_1",result_1)
print("the total price of product_2",result_2)
print("the total price of product_3",result_3)
print()
final_price=float(result_1)+float(result_2)+float(result_3)
print("total amount :",final_price)
